[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/trpc/*"
  to = "/.netlify/functions/trpc/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
